version: '3'

networks:
  totvs_tss:
    driver: bridge

services:
  db:
    image: postgres:12.3
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${POSTGRES_PROD_PORT}:5432
    volumes:
      - app-volume:/database/postgres:/var/lib/postgresql/data
    networks:
      - totvs_tss
    # Notice I don't even use a volume here since I don't care to persist test data between runs
  
  dbaccess:
    build: ./
    container_name: totvs_dbaccess
    ports:
      - 7890:7890
    networks:
      - totvs_tss
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}

volumes:
  app-volume: #      