version: '3'

services:

  dbaccess:
    build: ./
    ports:
      - 7890:7890
    env_file: ./.env

  database:
    build: ./postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}